api-server:
  host: https://stagingapi.watchmanpaymentsystems.com
  api_key: 2bfc3aea-cf37-4341-8139-c4db84be7e17
  secret: QsS/dF4IJWtq8gqGPyKp0+7MwM0MZC/mFsx9ggAGi7M=

file_path:
  case_file_path: ../data/case_data.xlsx
  report_data_file_path: ../Report/data/
  report_generate_file_data: ../Report/allure_raw/
  report_zip_file_path: ../Report/allure_raw/apiAutoTestReport.zip
  log_file_path: ../log/运行日志{time}.log